package com.alwyn.propertymanagement.exception;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class ErrorModel {
    
    private String code;

    private String message;


    // Getter and setter methods for 'code' and 'message' are automatically generated by Lombok.

}
