package com.alwyn.propertymanagement.exception;

import lombok.Getter;
import lombok.Setter;

@Getter

// Lombok annotation: Generates a getter method for each class field.
@Setter

// Lombok annotation: Generates a setter method for each class field.
public class ErrorModel {

    // A class to represent error information with 'code' and 'message' properties.
    
    private String code;
    
    // The error code associated with the error message.
    private String message;

    // The error message providing additional information about the error.

    // Getter and setter methods for 'code' and 'message' are automatically generated by Lombok.

}
